// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/27/2025, 5:31:44 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/var/www/html/Mostafa-Ali-Cv/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/Mostafa-Ali-Cv/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/Mostafa-Ali-Cv/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/Mostafa-Ali-Cv/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/Mostafa-Ali-Cv/app/plugins/**/*.{js,ts,mjs}","/var/www/html/Mostafa-Ali-Cv/app/composables/**/*.{js,ts,mjs}","/var/www/html/Mostafa-Ali-Cv/app/utils/**/*.{js,ts,mjs}","/var/www/html/Mostafa-Ali-Cv/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/Mostafa-Ali-Cv/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/Mostafa-Ali-Cv/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;